---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseVariableName:
        enabled: false
      CleanCode/ElseExpression:
        enabled: false
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2,WordPress"
ratings:
  paths:
  - "**.sass"
  - "**.js"
  - "**.php"
exclude_paths: 
  - "IBDE-plugin/plugin-activation/"
  - "IBDE-theme/bower_components/"
  - "IBDE-theme/config.rb"
  - "**.min.js"
  - "**.png"
  - "**.css"
