---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseVariableName:
        enabled: false
      Controversial/CamelCaseParameterName:
        enabled: false
      CleanCode/ElseExpression:
        enabled: false
  phpcodesniffer:
    enabled: true
    config:
      standard: "WordPress"
    checks:
      PEAR Functions FunctionCallSignature SpaceAfterOpenBracket:
        enabled: false
      PEAR Functions FunctionCallSignature SpaceBeforeOpenBracket:
        enabled: false
      PEAR Functions FunctionCallSignature SpaceBeforeCloseBracket:
        enabled: false
      PEAR Functions FunctionCallSignature Indent:
        enabled: false

      WordPress WhiteSpace ControlStructureSpacing NoSpaceAfterOpenParenthesis:
        enabled: false
      WordPress WhiteSpace ControlStructureSpacing NoSpaceBeforeCloseParenthesis:
        enabled: false
      WordPress WhiteSpace ControlStructureSpacing SpaceBeforeFunctionOpenParenthesis:
        enabled: false

      WordPress VIP RestrictedFunctions curl:
        enabled: false
      WordPress VIP RestrictedFunctions get_term_link:
        enabled: false
      WordPress VIP RestrictedFunctions term_exists:
        enabled: false
      WordPress VIP RestrictedFunctions wp_remote_get:
        enabled: false

      Squiz Strings DoubleQuoteUsage NotRequired:
        enabled: false
      Squiz Commenting InlineComment InvalidEndChar:
        enabled: false
      Squiz Commenting InlineComment NotCapital:
        enabled: false
      Squiz Functions FunctionDeclarationArgumentSpacing SpacingAfterOpen:
        enabled: false
      Squiz Functions FunctionDeclarationArgumentSpacing SpacingBeforeClose:
        enabled: false
      Squiz WhiteSpace SuperfluousWhitespace EndLine:
        enabled: false
      Squiz Functions MultiLineFunctionDeclaration BraceOnSameLine:
        enabled: false

      Generic WhiteSpace DisallowTabIndent NonIndentTabsUsed:
        enabled: false
      Generic WhiteSpace DisallowSpaceIndent SpacesUsed:
        enabled: false
      Generic WhiteSpace ScopeIndent IncorrectExact:
        enabled: false
      Generic WhiteSpace ScopeIndent Incorrect:
        enabled: false
ratings:
  paths:
  - "**.sass"
  - "**.js"
  - "**.php"
exclude_paths: 
  - "IBDE-plugin/plugin-activation/"
  - "IBDE-theme/bower_components/"
  - "IBDE-theme/config.rb"
  - "**.min.js"
  - "**.png"
  - "**.css"
