---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseVariableName:
        enabled: false
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.sass"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths: 
  - "IBDE-plugin/plugin-activation/"
  - "IBDE-theme/bower_components/"
  - "IBDE-theme/config.rb"
  - "*.min.js"
  - "*.png"
