---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseVariableName:
        enabled: false
      CleanCode/ElseExpression:
        enabled: false
  phpcodesniffer:
    enabled: true
    config:
      standard: "WordPress"
    checks:
      PEAR Functions FunctionCallSignature SpaceAfterOpenBracket:
        enabled: false
      PEAR Functions FunctionCallSignature SpaceBeforeOpenBracket:
        enabled: false
      WordPress WhiteSpace ControlStructureSpacing NoSpaceAfterOpenParenthesis:
        enabled: false
      WordPress WhiteSpace ControlStructureSpacing NoSpaceBeforeCloseParenthesis:
        enabled: false
      Squiz Strings DoubleQuoteUsage NotRequired:
        enabled: false
      Squiz Commenting InlineComment InvalidEndChar:
        enabled: false
      Squiz Commenting InlineComment NotCapital:
        enabled: false
      Generic WhiteSpace DisallowTabIndent NonIndentTabsUsed:
        enabled: false
      Generic WhiteSpace DisallowSpaceIndent SpacesUsed:
        enabled: false
      Squiz Functions MultiLineFunctionDeclaration BraceOnSameLine:
        enabled: false
ratings:
  paths:
  - "**.sass"
  - "**.js"
  - "**.php"
exclude_paths: 
  - "IBDE-plugin/plugin-activation/"
  - "IBDE-theme/bower_components/"
  - "IBDE-theme/config.rb"
  - "**.min.js"
  - "**.png"
  - "**.css"
