language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
install:
   - composer require codeclimate/php-test-reporter --dev
after_success:
  - vendor/bin/test-reporter
addons:
    code_climate:
        repo_token: 86665868bf0022a0f769fc8eacd364380f42dd6bba55d05a07d5d6cb0aa61285
